version: '3'

services:
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  
  spark:
    image: jupyter/all-spark-notebook:latest
    container_name: jupyter-spark
    restart: always
    volumes:
      - ./spark-notebooks:/home/jovyan/work
    ports:
      - 8888:8888
      - 4040:4040
      - 4041:4041

  postgres:
    image: postgres:latest
    container_name: pg_stage
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: root
    
